<?php

$plugin = array(
  'title' => t('Drunlab Main Layout'),
  'category' => t('Site templates'),
  'theme' => 'drunlab-main',
  'admin theme' => 'drunlab-main-admin',
  'admin css' => 'drunlab_main.admin.css',
  'icon' => '',
  'regions' => array(
    'header' => t('Header'),
    'left' => t('Left Sidebar'),
    'center' => t('Main Content'),
    'right' => t('Right Sidebar'),
    'footer' => t('Footer'),
  ),
);
